export primary_cluster_id=<YOUR_CLUSTER_ID_HERE>
export dr_cluster_id=<YOUR_CLUSTER_ID_HERE>
export CONFLUENT_CLOUD_API_KEY="<YOUR_CONFLUENT_CLOUD_API_KEY_HERE>"
export CONFLUENT_CLOUD_API_SECRET="<YOUR_CONFLUENT_CLOUD_API_SECRET_HERE>" 
export AWS_ACCESS_KEY_ID="<YOUR_AWS_ACCESS_API_KEY_HERE>"
export AWS_SECRET_ACCESS_KEY="<YOUR_AWS_ACCESS_API_SECRET_HERE>"
